name: ImageMap
version: 1.0
description: image map.
author: kubotan
main: space.gorogoro.imagemap.ImageMap
website: http://blog.gorogoro.space/

commands:
  imagemap:
    description: ポスターを取得します。
    usage: §c/<command> (map id) §7- 指定されたMAP IDのポスターを作成します。
